"""maha db upgrade

Revision ID: f6a81208107a
Revises: 0c5070e96b57
Create Date: 2018-08-28 16:05:04.039556

"""
from celery.worker.strategy import default

# revision identifiers, used by Alembic.
revision = 'f6a81208107a'
down_revision = '0c5070e96b57'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maha_registry',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registry_name', sa.String(length=50), nullable=True),
    sa.Column('registry_host', sa.String(length=256), nullable=True),
    sa.Column('registry_port', sa.Integer(), nullable=True),
    sa.Column('registry_endpoint', sa.String(length=256), nullable=True),
    sa.Column('metadata_last_refreshed', sa.DateTime(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('cache_timeout', sa.Integer(), nullable=True),
    sa.Column('sync_request_endpoint', sa.String(length=256), nullable=True),
    sa.Column('domain_endpoint', sa.String(length=256), nullable=True),
    sa.Column('white_list', sa.Text(), nullable=True),
    sa.Column('black_list', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], [u'ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], [u'ab_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registry_name')
    )
    
    op.create_table('cubes',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cube_name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_endpoint', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('schema', sa.Text(), nullable=True),
    sa.Column('cache_timeout', sa.Integer(), nullable=True),
    sa.Column('offset', sa.Integer(), nullable=True),
    sa.Column('cube_version', sa.Integer(), nullable=False, default=0),
    sa.Column('perm', sa.String(length=1000), nullable=True),
    sa.Column('registry_id', sa.Integer(), nullable=True),
    sa.Column('filter_select_enabled', sa.Boolean(), default=False),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('params', sa.String(length=1000), nullable = True),
    sa.ForeignKeyConstraint(['changed_by_fk'], [u'ab_user.id'], ),
    sa.ForeignKeyConstraint(['registry_id'], [u'maha_registry.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], [u'ab_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'ab_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cube_name')
    )
    
    op.create_table('cube_metrics',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=512), nullable=True),
    sa.Column('verbose_name', sa.String(length=1024), nullable=True),
    sa.Column('metric_type', sa.String(length=32), nullable=True),
    sa.Column('cube_name', sa.String(length=250), nullable=True),
    sa.Column('json', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('d3format', sa.String(length=128), nullable=True),
    sa.Column('cube_id', sa.Integer(), nullable=True),
    sa.Column('is_restricted', sa.Boolean(), nullable=True),
    sa.Column('warning_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], [u'ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], [u'ab_user.id'], ),
    sa.ForeignKeyConstraint(['cube_id'], [u'cubes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('maha_columns',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cube_name', sa.String(length=250), nullable=True),
    sa.Column('column_name', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('groupby', sa.Boolean(), nullable=True),
    sa.Column('count_distinct', sa.Boolean(), nullable=True),
    sa.Column('sum', sa.Boolean(), nullable=True),
    sa.Column('max', sa.Boolean(), nullable=True),
    sa.Column('min', sa.Boolean(), nullable=True),
    sa.Column('filterable', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('cube_id', sa.Integer(), nullable=True),
    sa.Column('verbose_name', sa.String(length=1024), nullable=True),
    sa.Column('avg', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], [u'ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], [u'ab_user.id'], ),
    sa.ForeignKeyConstraint(['cube_id'], [u'cubes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lookbacks',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cube_id', sa.Integer(), nullable=True),
    sa.Column('request_type', sa.String(length=32), nullable=True),
    sa.Column('grain', sa.String(length=32), nullable=True),
    sa.Column('lookback_days', sa.Integer(), nullable=True),
    sa.Column('max_window', sa.Integer(), nullable=True),
    sa.Column('created_by_fk', sa.Integer(), sa.ForeignKey("ab_user.id"), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), sa.ForeignKey("ab_user.id"), nullable=True),
    sa.ForeignKeyConstraint(['cube_id'], ['cubes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('lookbacks')
    op.drop_table('maha_columns')
    op.drop_table('cube_metrics')
    op.drop_table('cubes')
    op.drop_table('maha_registry')
    ### end Alembic commands ###
